[Autologin]
Relogin=false
Session=
User=

[General]
GreeterEnvironment=QML_DISABLE_DISTANCEFIELD=1
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=sddm-theme-mod
CursorSize=32
CursorTheme=aero-drop
Font=Segoe UI,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0

[Users]
MaximumUid=60513
MinimumUid=1000

[X11]
ServerArguments=-dpi 0
